Name: prod_deploy_workflow
SchemaVersion: '1.0'

Triggers:
  - Type: Push
    Branches:
      - main

Actions:
  Build_Dev:
    Identifier: aws/build@v1.0.0
    Inputs:
      Sources:
        - WorkflowSource
      Variables:
        - Name: AWS_ACCESS_KEY
          Value: ${Secrets.AWS_ACCESS_KEY}
        - Name: AWS_SECRET_KEY
          Value: ${Secrets.AWS_SECRET_KEY}
        - Name: AMPLIFY_ENV
          Value: prod
    Outputs:
      AutoDiscoverReports:
        Enabled: true
        ReportNamePrefix: amplify-rpt
    Configuration:
      Steps:
        - Run: npm install -g @aws-amplify/cli
        - Run: npm install
        - Run: set -e
        - Run: IFS='|'
        - Run: REACTCONFIG="{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm run-script build\",\"StartCommand\":\"npm run-script start\"}"
        - Run: AWSCLOUDFORMATIONCONFIG="{\"configLevel\":\"project\",\"useProfile\":false,\"profileName\":\"default\",\"accessKeyId\":\"$AWS_ACCESS_KEY\",\"secretAccessKey\":\"$AWS_SECRET_KEY\",\"region\":\"us-east-2\"}"
        - Run: AMPLIFY="{\"projectName\":\"amplifypipelinepoc\",\"envName\":\"$AMPLIFY_ENV\",\"defaultEditor\":\"code\"}"
        - Run: FRONTEND="{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":$REACTCONFIG}"
        - Run: PROVIDERS="{\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG}"
        - Run: amplify init --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --yes
        - Run: amplify push --allow-destructive-graphql-schema-updates --yes
    Compute:
      Type: Lambda
      Fleet: Linux.x86-64.Large
    Environment:
      Connections:
        - Role: AWSRoleForCodeCatalystSupport
          Name: 'BlogAccount'
      Name: Dev
